name: Scan Image

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [build-completed]
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: write
      id-token: write
      packages: read
      security-events: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 1

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@4484bf443b7858d89dd26541f46a3ae0794206a5 # v3.82.5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker Image
        run: docker pull ghcr.io/drengskapur/pptx2video:latest

      - name: Create SBOM
        uses: anchore/sbom-action@61119d458adab75f756bc0b9e4bde25725f86a7a # v0.17.2
        with:
          format: spdx-json
          output-file: "${{ github.event.repository.name }}-sbom.spdx.json"

      - name: Scan SBOM
        uses: anchore/scan-action@3343887d815d7b07465f6fdcd395bd66508d486a # v3
        with:
          sbom: "${{ github.event.repository.name }}-sbom.spdx.json"
          fail-build: false

      - name: Aqua Security Trivy Scan
        uses: aquasecurity/trivy-action@6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8 # v0.24.0
        with:
          image-ref: ghcr.io/drengskapur/pptx2video:latest
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy SARIF Report
        uses: github/codeql-action/upload-sarif@d97ba04b39135f37e9d60c84a6995bb18b7ac328 # v2
        with:
          sarif_file: trivy-results.sarif

      - name: Anchore Container Scan
        uses: anchore/scan-action@64a33b277ea7a1215a3c142735a1091341939ff5 # v4.1.2
        with:
          image: ghcr.io/drengskapur/pptx2video:latest
          output-format: sarif
          output: anchore-results.sarif
          fail-build: false

      - name: Upload Anchore SARIF Report
        uses: github/codeql-action/upload-sarif@d97ba04b39135f37e9d60c84a6995bb18b7ac328 # v2
        with:
          sarif_file: anchore-results.sarif

      - name: Initialize CodeQL
        uses: github/codeql-action/init@461ef6c76dfe95d5c364de2f431ddbd31a417628 # v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@461ef6c76dfe95d5c364de2f431ddbd31a417628 # v3
